driverClass=com.mysql.cj.jdbc.Driver
url=jdbc:mysql://localhost:3307/edufusion_iams_c?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
username=root
password=123456
